language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g npm
before_script:
  - cd node
  - npm install -g are-we-there-yet
  - npm install
script:
  - cd node
  - npm start &
  - sleep 5
  - npm test
notifications:
  email: false
