language: node_js
node_js:
  - "0.10"
  # - "0.11"
  # - "0.12"
before_install:
  - npm install -g npm
before_script:
  - cd node
  - npm install -g are-we-there-yet
  - npm install
# script:
#   - npm test
